##auto deploy yml file v1.1.9##

deployment:
  tasks:
    - export DEPLOYPATH=/home/martindw/public_html/wp-content/themes/techhobbyist_version_8
    - /bin/cp -R wp-content $DEPLOYPATH
    - /bin/cp -R * $DEPLOYPATH