##auto deploy yml file v1.1.1##

deployment:
  tasks:
    - export DEPLOYPATH=/home/martindw/public_html/wp-content/themes/techhobbyist_version_8
    - /bin/cp -R .vscode $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R fonts $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R includes $DEPLOYPATH
    - /bin/cp -R template-parts $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH